"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = {
  DATA_LOADED: "DATA_LOADED",
  ACTION_START: "ACTION_START",
  AUDIO_LOADED: "AUDIO_LOADED",
  AUDIO_FINISHED: "AUDIO_FINISHED",
  IMAGERY_LOADED: "IMAGERY_LOADED",
  PLAYING: "PLAYING",
  STATUS: "STATUS",
  DISPLAY_ABOUT: "DISPLAY_ABOUT",
  CLOSE_ABOUT: "CLOSE_ABOUT"
};